=== blairisme/fhirwork/application/src/test/resources/Patient.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://hl7.org/fhir/json-schema/Patient",
  "description": "Modified Patient's FHIR Data Schema",
  "type": "object",
  "properties": {
    "resourceType": {
      "description": "This is a Patient resource",
      "type": "string",
      "enum": [
        "Patient"
      ]
    },
    "identifier": {
      "description": "An identifier for this patient.",
      "type": "array",
      "items": { "type": "object"}
    },
    "active": {
      "description": "Whether this patient record is in active use.",
      "type": "boolean"
    },
    "_active": {
      "description": "Extensions for active"
    },
    "name": {
      "description": "A name associated with the individual.",
      "type": "array",
      "items": {"type": "object"}
    },
    "telecom": {
      "description": "A contact detail (e.g. a telephone number or an email address) by which the individual may be contacted.",
      "type": "array",
      "items": {"type": "object"}
    },
    "gender": {
      "description": "Administrative Gender - the gender that the patient is considered to have for administration and record keeping purposes.",
      "enum": [
        "male",
        "female",
        "other",
        "unknown"
      ],
      "type": "string"
    },
    "birthDate": {
      "description": "The date of birth for the individual.",
      "type": "string",
      "pattern": "-?[0-9]{4}(-(0[1-9]|1[0-2])(-(0[0-9]|[1-2][0-9]|3[0-1]))?)?"
    },
    "deceasedBoolean": {
      "description": "Indicates if the individual is deceased or not.",
      "type": "boolean"
    },
    "deceasedDateTime": {
      "description": "Indicates if the individual is deceased or not.",
      "pattern": "-?[0-9]{4}(-(0[1-9]|1[0-2])(-(0[0-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)))?)?)?",
      "type": "string"
    },
    "address": {
      "description": "Addresses for the individual.",
      "type": "array",
      "items": {"type": "object"}
    },
    "maritalStatus": {
      "description": "This field contains a patient's most recent marital (civil) status."
    },
    "multipleBirthBoolean": {
      "description": "Indicates whether the patient is part of a multiple (bool) or indicates the actual birth order (integer).",
      "type": "boolean"
    },
    "multipleBirthInteger": {
      "description": "Indicates whether the patient is part of a multiple (bool) or indicates the actual birth order (integer).",
      "pattern": "-?([0]|([1-9][0-9]*))",
      "type": "number"
    },
    "contact": {
      "description": "A contact party (e.g. guardian, partner, friend) for the patient.",
      "type": "array",
      "items": {"type": "object"}
    },
    "animal": {
      "description": "This patient is known to be an animal."
    },
    "communication": {
      "description": "Languages which may be used to communicate with the patient about his or her health.",
      "type": "array",
      "items": {"type": "object"}
    },
    "generalPractitioner": {
      "description": "Patient's nominated care provider.",
      "type": "array",
      "items": {"type": "object"}
    },
    "managingOrganization": {
      "description": "Organization that is the custodian of the patient record."
    },
    "link": {
      "description": "Link to another patient resource that concerns the same actual patient.",
      "type": "array",
      "items": {"type": "object"}
    },
    "meta": {
      "type": "object",
      "properties": {
        "lastUpdated": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "id": {
      "description": "ID",
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [
    "resourceType"
  ]
}

=== blairisme/fhirwork/application/resource/updateResourceFhir.json
{
  "resourceType": "Patient",
  "identifier": [
    {
      "system": "SSN",
      "value": "568754549875445698798988873"
    }
  ],
  "name": [
    {
      "use": "usual",
      "family": ["Williams"],
      "given": [
        "Kate",
        "Mary"
      ],
      "prefix": [
        "Miss"
      ]
    },
    {
      "use": "maiden",
      "family": ["Kat"]
    }
  ],
  "telecom": [
    {
      "system": "email",
      "value": "katewilliams@gmail.com"
    },
    {
      "system": "phone",
      "value": "6789475459787"
    }
  ],
  "gender": "female",
  "birthDate": "1970-09-24",
  "deceasedDateTime": "1982-08-25T07:06:12-04:00",
  "address": [
    {
      "text": "Kings Cross Penton Rise London London 589632 UK",
      "line": [
        "Kings Cross",
        "Penton Rise"
      ],
      "city": "London",
      "state": "London",
      "postalCode": "589632",
      "country": "UK"
    }
  ],
  "maritalStatus": {
    "coding": [
	    {	
		"system": "http://hl7.org/fhir/v3/MaritalStatus",
		"code": "D"
	    }
    ]
  },
  "multipleBirthInteger": 2
}
